In [1]:
import pandas as pd
import yfinance as yf
from datetime import date, timedelta

# define the time period for the data
end_date = date.today().strftime("%Y-%m-%d")
start_date = (date.today() - timedelta(days=365)).strftime("%Y-%m-%d")

# list of stock tickers to download
tickers = ['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS']

data = yf.download(tickers, start=start_date, end=end_date, progress=False)

# reset index to bring  = y.doto the (ticker for the melt function
data = data.reset_index()

# melt the DataFrame to make it long format where each row is a unique combination of Date, Ticker, and attributes
t=start_date, end=end_date, progress=False)

# reset index to bring Date in
# pivot the melted DataFrame to have the attributes (Open, High, Low, etc.) as columns
data_pivoted = data_melted.pivot_table(index=['Date', 'Ticker'], columns='Attribute', values='value', aggfunc='first')

# reset index to turn multi-index into columns
stock_data = data_pivoted.reset_index()

print(stock_data.head())

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['Date']"

In [2]:
import pandas as pd
import yfinance as yf
from datetime import date, timedelta

# Define the time period for the data
end_date = date.today().strftime("%Y-%m-%d")
start_date = (date.today() - timedelta(days=365)).strftime("%Y-%m-%d")

# List of stock tickers to download
tickers = ['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS']

# Download the stock data
data = yf.download(tickers, start=start_date, end=end_date, progress=False)

# Reset index to bring Date into the columns
data = data.reset_index()

# Check the columns and first few rows of the DataFrame
print("Columns:", data.columns)
print(data.head())

# Melt the DataFrame to make it long format where each row is a unique combination of Date, Ticker, and attributes
# Since 'var_name' should be a single string, we need to handle this differently
data_melted = data.melt(id_vars=['Date'], var_name='Attribute', value_name='value')

# Extract Ticker and Attribute from the 'Attribute' column
data_melted[['Ticker', 'Attribute']] = data_melted['Attribute'].str.split(' ', 1, expand=True)

# Pivot the melted DataFrame to have the attributes (Open, High, Low, etc.) as columns
data_pivoted = data_melted.pivot_table(index=['Date', 'Ticker'], columns='Attribute', values='value', aggfunc='first')

# Reset index to turn multi-index into columns
stock_data = data_pivoted.reset_index()

print(stock_data.head())

Columns: MultiIndex([(     'Date',            ''),
            ('Adj Close', 'HDFCBANK.NS'),
            ('Adj Close',     'INFY.NS'),
            ('Adj Close', 'RELIANCE.NS'),
            ('Adj Close',      'TCS.NS'),
            (    'Close', 'HDFCBANK.NS'),
            (    'Close',     'INFY.NS'),
            (    'Close', 'RELIANCE.NS'),
            (    'Close',      'TCS.NS'),
            (     'High', 'HDFCBANK.NS'),
            (     'High',     'INFY.NS'),
            (     'High', 'RELIANCE.NS'),
            (     'High',      'TCS.NS'),
            (      'Low', 'HDFCBANK.NS'),
            (      'Low',     'INFY.NS'),
            (      'Low', 'RELIANCE.NS'),
            (      'Low',      'TCS.NS'),
            (     'Open', 'HDFCBANK.NS'),
            (     'Open',     'INFY.NS'),
            (     'Open', 'RELIANCE.NS'),
            (     'Open',      'TCS.NS'),
            (   'Volume', 'HDFCBANK.NS'),
            (   'Volume',     'INFY.NS'),
            (   'Volume', 'RELIANCE.NS'),
            (   'Volume',      'TCS.NS')],
           names=['Price', 'Ticker'])
Price        Date    Adj Close                                         \
Ticker             HDFCBANK.NS      INFY.NS  RELIANCE.NS       TCS.NS
0      2023-08-14  1589.198853  1368.032837  2568.177979  3392.482178
1      2023-08-16  1584.562012  1392.525879  2566.085449  3400.889648
2      2023-08-17  1575.782104  1385.703247  2529.066162  3378.616455
3      2023-08-18  1569.320190  1363.369751  2547.800049  3311.108154
4      2023-08-21  1568.087036  1379.665894  2520.000000  3345.083496

Price         Close                                                High  ...  \
Ticker  HDFCBANK.NS      INFY.NS  RELIANCE.NS       TCS.NS  HDFCBANK.NS  ...
0       1610.900024  1393.550049  2577.250000  3449.850098  1615.000000  ...
1       1606.199951  1418.500000  2575.149902  3458.399902  1609.650024  ...
2       1597.300049  1411.550049  2538.000000  3435.750000  1609.900024  ...
3       1590.750000  1388.800049  2556.800049  3367.100098  1596.300049  ...
4       1589.500000  1405.400024  2520.000000  3401.649902  1600.500000  ...

Price           Low                      Open                            \
Ticker  RELIANCE.NS       TCS.NS  HDFCBANK.NS      INFY.NS  RELIANCE.NS
0       2525.000000  3411.000000  1611.000000  1371.849976  2539.000000
1       2551.000000  3435.199951  1583.099976  1410.800049  2551.000000
2       2532.850098  3413.199951  1597.599976  1420.000000  2567.100098
3       2508.550049  3356.500000  1587.550049  1403.699951  2531.250000
4       2515.649902  3372.000000  1600.500000  1389.750000  2539.949951

Price                    Volume
Ticker       TCS.NS HDFCBANK.NS  INFY.NS RELIANCE.NS   TCS.NS
0       3440.699951    15652205  4304135     4787906  1190425
1       3450.000000    17068771  7735313     5101556  1328445
2       3455.000000    26442020  5618346     6836872  1843241
3       3410.000000    12816683  5134103     9319989  2526749
4       3375.000000    10918635  3032722     4610873  1375579

[5 rows x 25 columns]

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['Date']"

In [3]:
import pandas as pd
import yfinance as yf
from datetime import date, timedelta

# Define the time period for the data
end_date = date.today().strftime("%Y-%m-%d")
start_date = (date.today() - timedelta(days=365)).strftime("%Y-%m-%d")

# List of stock tickers to download
tickers = ['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS']

# Download the stock data
data = yf.download(tickers, start=start_date, end=end_date, progress=False)

# Reset index to bring Date into the columns
data = data.reset_index()

# Print column names to verify
print("Columns:", data.columns)

# Melt the DataFrame to make it long format where each row is a unique combination of Date, Ticker, and attributes
data_melted = data.melt(id_vars=['Date', 'Ticker'], var_name='Attribute', value_name='Value')

# Pivot the melted DataFrame to have the attributes (Open, High, Low, etc.) as columns
data_pivoted = data_melted.pivot_table(index=['Date', 'Ticker'], columns='Attribute', values='Value', aggfunc='first')

# Reset index to turn multi-index into columns
stock_data = data_pivoted.reset_index()

print(stock_data.head())

Columns: MultiIndex([(     'Date',            ''),
            ('Adj Close', 'HDFCBANK.NS'),
            ('Adj Close',     'INFY.NS'),
            ('Adj Close', 'RELIANCE.NS'),
            ('Adj Close',      'TCS.NS'),
            (    'Close', 'HDFCBANK.NS'),
            (    'Close',     'INFY.NS'),
            (    'Close', 'RELIANCE.NS'),
            (    'Close',      'TCS.NS'),
            (     'High', 'HDFCBANK.NS'),
            (     'High',     'INFY.NS'),
            (     'High', 'RELIANCE.NS'),
            (     'High',      'TCS.NS'),
            (      'Low', 'HDFCBANK.NS'),
            (      'Low',     'INFY.NS'),
            (      'Low', 'RELIANCE.NS'),
            (      'Low',      'TCS.NS'),
            (     'Open', 'HDFCBANK.NS'),
            (     'Open',     'INFY.NS'),
            (     'Open', 'RELIANCE.NS'),
            (     'Open',      'TCS.NS'),
            (   'Volume', 'HDFCBANK.NS'),
            (   'Volume',     'INFY.NS'),
            (   'Volume', 'RELIANCE.NS'),
            (   'Volume',      'TCS.NS')],
           names=['Price', 'Ticker'])

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['Date', 'Ticker']"

In [4]:
import pandas as pd
import yfinance as yf
from datetime import date, timedelta

# Define the time period for the data
end_date = date.today().strftime("%Y-%m-%d")
start_date = (date.today() - timedelta(days=365)).strftime("%Y-%m-%d")

# List of stock tickers to download
tickers = ['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS']

# Download the stock data
data = yf.download(tickers, start=start_date, end=end_date, progress=False)

# Reset index to bring Date into the columns
data = data.reset_index()

# Print column names to verify
print("Columns:", data.columns)

# Melt the DataFrame
data_melted = data.melt(id_vars=['Date', 'Ticker'], var_name='Attribute', value_name='Value')

# Pivot the melted DataFrame to have the attributes (Open, High, Low, etc.) as columns
data_pivoted = data_melted.pivot_table(index=['Date', 'Ticker'], columns='Attribute', values='Value', aggfunc='first')

# Reset index to turn multi-index into columns
stock_data = data_pivoted.reset_index()

print(stock_data.head())

Columns: MultiIndex([(     'Date',            ''),
            ('Adj Close', 'HDFCBANK.NS'),
            ('Adj Close',     'INFY.NS'),
            ('Adj Close', 'RELIANCE.NS'),
            ('Adj Close',      'TCS.NS'),
            (    'Close', 'HDFCBANK.NS'),
            (    'Close',     'INFY.NS'),
            (    'Close', 'RELIANCE.NS'),
            (    'Close',      'TCS.NS'),
            (     'High', 'HDFCBANK.NS'),
            (     'High',     'INFY.NS'),
            (     'High', 'RELIANCE.NS'),
            (     'High',      'TCS.NS'),
            (      'Low', 'HDFCBANK.NS'),
            (      'Low',     'INFY.NS'),
            (      'Low', 'RELIANCE.NS'),
            (      'Low',      'TCS.NS'),
            (     'Open', 'HDFCBANK.NS'),
            (     'Open',     'INFY.NS'),
            (     'Open', 'RELIANCE.NS'),
            (     'Open',      'TCS.NS'),
            (   'Volume', 'HDFCBANK.NS'),
            (   'Volume',     'INFY.NS'),
            (   'Volume', 'RELIANCE.NS'),
            (   'Volume',      'TCS.NS')],
           names=['Price', 'Ticker'])

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['Date', 'Ticker']"